# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
[build]
  [functions]
    directory = "functions"
    directory = "/"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

